<a href="https://colab.research.google.com/github/wancianyu/114-2-programming-language/blob/main/HW1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1jR3qRQr2ZvWYKNuv8wen_-eTZWdc5a-LLvH7iymn2zw/edit?usp=sharing

In [83]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [84]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1WOosup4b5gsHYYyHu0lGsViyyJ2g_KBmnWrsM-EMsKE/edit?gid=0#gid=0')

In [85]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

           日期     時間  分類  品項    金額    付款人  地點 支付方式        備註
0  2026-03-13  18:30  交通  高鐵  1200  Doris  高雄  信用卡
1  2026-05-30   5:30  食物  麵包    50    Jae           幫Doris買的

In [86]:
import datetime

In [87]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

category = input("請輸入分類：")
item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
person = input("請輸入付款人：")
place = input("請輸入地點：")
payment = input("請輸入支付方式：")
other = input("請輸入備註：")

請輸入日期 (格式：YYYY-MM-DD): 2026-01-10
請輸入時間 (格式：HH:MM): 12:30
請輸入分類：
請輸入品項: 化妝品
請輸入金額: 300
請輸入付款人：Doris
請輸入地點：藥妝店
請輸入支付方式：現金
請輸入備註：

In [88]:
date_str

'2026-01-10'

In [89]:
time_str

'12:30'

In [90]:
category

''

In [91]:
item

'化妝品'

In [92]:
amount

300.0

In [93]:
person

'Doris'

In [94]:
place

'藥妝店'

In [95]:
payment

'現金'

In [96]:
other

''

In [97]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': category,
    '品項': item,
    '金額': amount,
    '付款人': person,
    '地點': place,
    '支付方式': payment,
    '備註': other
}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [98]:
df

           日期     時間  分類   品項     金額    付款人   地點 支付方式        備註
0  2026-03-13  18:30  交通   高鐵   1200  Doris   高雄  信用卡
1  2026-05-30   5:30  食物   麵包     50    Jae            幫Doris買的
2  2026-01-10  12:30      化妝品  300.0  Doris  藥妝店   現金

In [99]:
# 將NaN(非數值)的資料替換成空字串
data_to_write = new_data.fillna('').values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：將資料寫入工作表
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！